_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.6
            "8":
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
environment:
    value: WatchAndHelp1
max_episode_length:
    value: 100
