FROM ubuntu:22.04
# FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-devel

RUN apt-get update && apt-get install -y \
    software-properties-common \
    wget \
    curl \
    python3 \
    python3-pip \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libxi6 \
    libgl1-mesa-glx \
    && rm -rf /var/lib/apt/lists/*

COPY ./CitySample /usr/local/bin/CitySample
COPY ./mcts.py /usr/src/app/mcts.py
COPY ./requirements.txt /usr/src/app/requirements.txt
COPY ./utils.py /usr/src/app/utils.py

RUN pip3 install -r /usr/src/app/requirements.txt

RUN chmod +x /usr/local/bin/CitySample

WORKDIR /usr/src/app

CMD ["/bin/bash", "-c", "/usr/local/bin/CitySample & python3 mcts.py"]
