_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.6
            "8":
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
agent_id:
    value: 0
c_base:
    value: 19652
c_init:
    value: 1.25
discount:
    value: 1
env_name:
    value: WatchAndHelp1
max_episode_length:
    value: 100
max_rollout_step:
    value: 5
num_simulation:
    value: 1000
seed:
    value: 1
